### ISSUE TITLE
[A11] SystemException: [CS1061] Type `GUIWorkItem` does not contain a definition for `Assign`

### ISSUE THREAD

**Issue by joestringer** [realworld666/SIncLib#1]
Version: Alpha 11.6.11

After startup, from the `Mods` menu, this mod shows up under the `Error` tab. Here's the error:

SystemException: [CS1061] Type `GUIWorkItem` does not contain a definition for `Assign` and no extension method `Assign` of type `GUIWorkItem` could be found. Are you missing an assembly reference? In <path-to-SincLibAutoDevUI.cs> at [269, 30] 

Must be referring to this:
https://github.com/realworld666/SIncLib/blob/10d31023d51314b4ff5613d57c6327b3b72d57de/SIncLib/SIncLibAutoDevUI.cs#L269

**Comment by ghost** [comment]
Im working on a A11 fix for this.

**Comment by ghost** [comment]
Expect a A11 version later next week.

**Comment by realworld666** [comment]
Thanks. I've not had time to look at this mod for some time. If you make a PR I can pull it in

**Comment by ghost** [comment]
A11 has broken the entire mod, the way software is created has totally changed, i think SIncLib will have to be redone. A bug fix wont work here.

**Comment by ghost** [comment]
I'm going to drop this PR currently. Too much and i've already got tons to do.

**Comment by joestringer** [comment]
Out of curiousity, is there a particular page that describes the new modding APIs? Or what's the process of figuring it out, just looking at exported symbols?

**Comment by realworld666** [comment]
https://swinc.net/wiki/index.php?title=Modding though I dont know how up to date it is

**Comment by ghost** [comment]
The modding API hasn't changed a single bit, but the game source code has changed a shit ton, checkout the official discord here: https://discordapp.com/invite/VsPgYKS

Alot of modders can probably help you.

**Comment by ghost** [comment]
For example, there is no beta, alpha or delay for software development now, it's really changed.

**Comment by realworld666** [comment]
So its been a while but I'm updating this for A11 now. I've got it compiling but theres a runtime error I need to investigate

**Comment by realworld666** [comment]
I've removed the auto dev stuff as much of the functionality is now covered by the main game but I've fixed up the rest of the mod and will add some new things in the future hopefully
